services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: ideal-api
    restart: unless-stopped
    env_file:
      - .env
      - apps/api/.env
    ports:
      - "3333:3333"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: ideal-web
    restart: unless-stopped
    env_file:
      - apps/web/.env.local
    ports:
      - "3100:3000"
    depends_on:
      - api
